
#? ==========================================================================================
                                            #* File O/I  
#?===========================================================================================??
#! File i/o is use to read, write, append and many to another file 
#todo WRITE :-
#? w = "I am a good boy"
#? with open("file.txt", "w") as f:
#?     f.write(w)
#! OR 
#? w = "hello"
#? f = open("tex.txt", "w")
#? f.write(w)
#?f.close()

#todo READ :-
# ?with open("file.txt", "r") as f:
# ?    r = f.read()
# ?print(r)
 #?! OR 
#? f = open("tex.txt", "r")
#?? r = f.read()
#?? f.close()
#?? print(r)
#todo APPEND :-
#? ?a = "Hellow I appended"
#?? with open("file.txt", "a") as f:
#??     f.write(a)

#? f = open("tex.txt", "a")
#? f.write("helllllo")
#? f.close()
